// <auto-generated />
using System;
using AccountingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountingAPI.Migrations
{
    [DbContext(typeof(AccountingDBContext))]
    [Migration("20260122074101_Account_ParentId_Isnullable")]
    partial class Account_ParentId_Isnullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountingAPI.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CId");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool?>("OpeningAmountType")
                        .HasColumnType("bit");

                    b.Property<string>("ParentCid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Parent_CId");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("Parent_Id");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "Id" }, "IX_Accounts");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountingAPI.Data.Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountCid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Account_CId");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("Account_Id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.Property<int>("YearId")
                        .HasColumnType("int")
                        .HasColumnName("Year_Id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Ledgers");
                });

            modelBuilder.Entity("AccountingAPI.Data.Account", b =>
                {
                    b.HasOne("AccountingAPI.Data.Account", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AccountingAPI.Data.Ledger", b =>
                {
                    b.HasOne("AccountingAPI.Data.Account", "Account")
                        .WithMany("Ledgers")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Ledger_Accunts")
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountingAPI.Data.Account", b =>
                {
                    b.Navigation("Ledgers");
                });
#pragma warning restore 612, 618
        }
    }
}
